#!/bin/bash

# Script Name: revWhois
# Description: A script for reverse whois according IP, Name
# Author: Hossein Sh.
# Created: 2023 M05 29, Tue 08:47
# Version: v1.0.0

RED='\033[0;31m'   # Red color
GREEN='\033[0;35m' # Green color
ORANGE='\033[0;33m' # Green color
NC='\033[0m'       # No color.

while read -r IP_ADDRESS; do

		#RIPE
		whois $IP_ADDRESS | awk -F':' '/admin-c:/ { print $2 }' | tr -d ' ' | while IFS= read -r admin_c; do                           ok
      whois -h whois.ripe.net -- "-i person $admin_c" | awk -F':' '/inetnum:/ { print $2 }' | tr -d ' '
    done
    whois -h whois.ripe.net $IP_ADDRESS | grep inet6num | cut -d':' -f2- | tr -d ' '
    #ARIN
    whois -h whois.arin.net "n $IP_ADDRESS" | grep -i "^$IP_ADDRESS" | sed 's/.*)//' | tr -d ' '
    #APNIC
    whois -h whois.apnic.net $IP_ADDRESS | grep inetnum | cut -d':' -f2 | tr -d ' '
    # whois -h whois.apnic.net $IP_ADDRESS | grep inet6num | cut -d':' -f2- | tr -d ' '
    #AFRINIC
    whois -h whois.afrinic.net $IP_ADDRESS | grep inetnum | cut -d':' -f2 | tr -d ' '
    # whois -h whois.afrinic.net $IP_ADDRESS | grep inet6num | cut -d':' -f2- | tr -d ' '

done
